name: Deploy to Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Subiendo a Surge
        run: |
          npm install -g surge
          surge ./ --domain electiva2.surge.sh --token ${{ secrets.SURGE_TOKEN }}
